# Generated by Django 2.1.7 on 2019-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190404_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wCity', models.CharField(max_length=20)),
                ('wDate', models.CharField(max_length=20)),
                ('wWeather', models.CharField(max_length=20)),
                ('wTemp', models.CharField(max_length=20)),
            ],
        ),
    ]
