# Generated by Django 2.1.7 on 2019-04-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_weather'),
    ]

    operations = [
    ]
